import os
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente VARCHAR(12) PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS veterinarios (
    id_veterinario VARCHAR(11) PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    especialidad VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS mascotas (
    id_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    especie VARCHAR(80) NOT NULL,
    raza VARCHAR(80) NOT NULL,
    edad INTEGER NOT NULL CHECK (edad BETWEEN 0 AND 150),
    peso NUMERIC(8, 2) NOT NULL CHECK (peso > 0 AND peso <= 1000),
    id_cliente VARCHAR(12) NOT NULL REFERENCES clientes(id_cliente)
);

CREATE TABLE IF NOT EXISTS citas (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    id_mascota BIGINT NOT NULL REFERENCES mascotas(id_mascota),
    id_veterinario VARCHAR(11) NOT NULL REFERENCES veterinarios(id_veterinario),
    motivo VARCHAR(240) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Programada',
    CONSTRAINT citas_estado_valido CHECK (estado IN ('Programada', 'Completada'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_citas_veterinario_horario_programada
ON citas (id_veterinario, fecha, hora)
WHERE estado = 'Programada';

CREATE TABLE IF NOT EXISTS registros_clinicos (
    id_registro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita BIGINT NOT NULL REFERENCES citas(id_cita),
    id_mascota BIGINT NOT NULL REFERENCES mascotas(id_mascota),
    fecha DATE NOT NULL,
    diagnostico VARCHAR(500) NOT NULL,
    tratamiento VARCHAR(500) NOT NULL,
    observaciones VARCHAR(500) NOT NULL DEFAULT ''
);
"""


def get_database_url() -> str:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL is required. Use a PostgreSQL/Neon URL.")
    return database_url


@contextmanager
def get_connection():
    connection = psycopg.connect(get_database_url(), row_factory=dict_row)
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def initialize_database() -> None:
    with get_connection() as connection:
        connection.execute(SCHEMA_SQL)
